#%RAML 1.0 Trait
queryParameters:
  departureLocationCode:
    type: string
    example: "BEN-SG"
    description: starting location

  destinationLocationCode:
    type: string
    example: "KLG-MY"
    description: final destination